name: Deploy to VM

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.txt
          chmod 600 key.txt

      - name: Deploy to VM
        run: |
          ssh -v -p 22 lms@164.92.75.149 -i key.txt -o StrictHostKeyChecking=no 'echo "lms" | sudo -S rm -rf /app/test-app && sudo -S mkdir -p /app && sudo -S chown lms:lms-group /app && cd /app && git clone https://github.com/somirayan/test-app.git && cd test-app && ./deploy.sh'

