name: Deploy to VM

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 164.92.75.149 >> ~/.ssh/known_hosts

      - name: Debug SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY"

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa lms@164.92.75.149 'cd /app/lms.jar && docker-compose up -d'
